name: Cypress CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Insatall modules
              run: yarn install
            - name: Run Cypress tests
              run: npx cypress run
            - name: Build
              run: yarn run build
              env:
                  NODE_ENV: production

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Install Modules
              run: yarn install

            - name: Run lint
              run: yarn run lint
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: preview
            url: ${{ steps.deploy.outputs.url }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Install Modules
              run: yarn install
            - name: Install Vercel CLI
              run: yarn add global vercel@latest

            # Pull Preview
            - name: Pull Preview
              if: github.event_name == 'pull_request' && github.event.pull_request.merged != true
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            # Pull Production
            - name: Pull Production
              if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            # Build Preview
            - name: Build Preview
              if: github.event_name == 'pull_request' && github.event.pull_request.merged != true
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            # Build Production
            - name: Build Production
              if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            # Deploy Preview
            - name: Deploy Preview
              if: github.event_name == 'pull_request' && github.event.pull_request.merged != true
              id: deploy
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

            # Deploy Production
            - name: Deploy Production
              if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
